// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIudoq3ofvM8OEMfVr2_ckt1Js0rg1WnI',
    appId: '1:659226229799:android:8a3541371590549d2a6202',
    messagingSenderId: '659226229799',
    projectId: 'whereisit-b0680',
    storageBucket: 'whereisit-b0680.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKlFWu9JfGj_o0UJt345YNmRIjz4MImS8',
    appId: '1:659226229799:web:d81a35c403d37c662a6202',
    messagingSenderId: '659226229799',
    projectId: 'whereisit-b0680',
    authDomain: 'whereisit-b0680.firebaseapp.com',
    storageBucket: 'whereisit-b0680.firebasestorage.app',
    measurementId: 'G-CNCEY7MP45',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKlFWu9JfGj_o0UJt345YNmRIjz4MImS8',
    appId: '1:659226229799:web:f50410d7638dec0c2a6202',
    messagingSenderId: '659226229799',
    projectId: 'whereisit-b0680',
    authDomain: 'whereisit-b0680.firebaseapp.com',
    storageBucket: 'whereisit-b0680.firebasestorage.app',
    measurementId: 'G-ZLNXQY7V85',
  );
}
